update_id: 0  #INT: this is used to compare to a tool update id if it's different the tool gets updated.
settings:
  showCooldownTimeRemaining: true
  CooldownRemainingMessage: "§c§l[MagicalTools] §r§cYou can't use it! Cooldown remaining: {time}s."
  NoPermissionsMessage: "§c§l[MagicalTools] §r§cYou don't have permissions to execute this command!"
  ToolDisabledMessage: "§c§l[MagicalTools] §r§cThis Magical Tool is disabled. You can't use it!"
tools:
  lightningsword: #DO NOT CHANGE! ID of the tool. You can only add new custom attributes by adding existing Tool id to the config.
    disabled: false #BOOLEAN: true/false
    label: "§b§lLightning Sword" #STRING: name of the tool in the inventory
    lore: #the description of the tool in the inventory
      - "§850% to strike your enemy with lightning!"
      - "§82 second cooldown on the effect."
      - "§8Use it carefully."
    material: "IRON_SWORD" #STRING: the item material (for example Diamond Sword, or Blaze rot, etc...)
    unbreakable: true #BOOLEAN: true/false
    shine: false #BOOLEAN: true/false
    custom_model: true #BOOLEAN: true/false
    meleedamage: 1 #DOUBLE
    cooldown: 3000 #INTEGER
    #Unique attributes to this item
    chance: 50 #INTEGER
  raygun: #DO NOT CHANGE! ID of the tool. You can only add new custom attributes by adding existing Tool id to the config.
    disabled: false
    label: "§2§lRaygun"
    lore:
      - "§8Shoots laser with powerful gamma rays."
      - "§8Can't penetrate any solid blocks."
    material: "ECHO_SHARD"
    unbreakable: true
    shine: true
    custom_model: true
    meleedamage: 1
    cooldown: 2000
    #Unique attributes to this item
    laserdamage: 10 #DOUBLE
  magicalpickaxe: #DO NOT CHANGE! ID of the tool. You can only add new custom attributes by adding existing Tool id to the config.
    disabled: false
    label: "§6§lFlaming Pickaxe"
    lore:
      - "§8Special pickaxe that destroys blocks around it."
    material: "GOLDEN_PICKAXE"
    unbreakable: true
    shine: true
    custom_model: false
    meleedamage: 3
    cooldown: 0
    #Unique attributes to this item
    mining_radius: 1 #INTEGER
    destroy_particle: "LAVA" #STRING
  randomsword: #DO NOT CHANGE! ID of the tool. You can only add new custom attributes by adding existing Tool id to the config.
    disabled: false
    label: "§f§k§lkkk §r§4§lGambler's Axe §f§k§lkkk"
    lore:
      - "§8Very heavy axe with a strong hit."
      - "§825% chance to deal damage."
      - "§81 second cooldown."
    material: "NETHERITE_AXE"
    unbreakable: true
    shine: true
    custom_model: false
    meleedamage: 30
    cooldown: 1000
    #Unique attributes to this item
    chance: 25
    success_message: "§6§lBaaam.... Smash!" #STRING
    loose_message: "§7§lWhifff... Missed!" #STRING
  mobcatcher: #DO NOT CHANGE! ID of the tool. You can only add new custom attributes by adding existing Tool id to the config.
    disabled: false
    label: "§f§lMob Catcher"
    lore:
      - "§8Turns mob into a spawn egg."
    material: "SNOWBALL"
    unbreakable: true
    shine: true
    custom_model: false
    meleedamage: 0
    cooldown: 0
    #Unique attributes to this item
    catch_message: "§6You've just captured a §l{caught_entity}." #STRING
  gravitypipe: #DO NOT CHANGE! ID of the tool. You can only add new custom attributes by adding existing Tool id to the config.
    disabled: false
    label: "§b§lGravity§6§lPipe"
    lore:
      - "§8A pipe that transfers kinetic energy."
      - "§80 attack damage!"
      - "§81 second cooldown."
    material: "BLAZE_ROD"
    unbreakable: true
    shine: true
    custom_model: false
    meleedamage: 0
    cooldown: 1000
    #Unique attributes to this item
    gravity_multiplier: 10 #DOUBLE